version: '3'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/app/src
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: root
      DB_PASSWORD: password
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password